export enum TestIds {
  form = 'form',
  formCard = 'formCard',
  formCardList = 'formCardList',
  name = 'name',
  surname = 'surname',
  date = 'date',
  image = 'image',
  error = 'error',
  consent = 'consent',
  country = 'country',
  submit = 'submit',
  successMessage = 'successMessage',
  gender = 'gender',
  cardImg = 'img',
  card = 'card',
  cards = 'cards',
  home = 'home',
  about = 'about',
  errorPage = 'errorPage',
  forms = 'forms',
  spinner = 'spinner',
  overlay = 'overlay',
  modal = 'modal',
  modalImg = 'modal-img',
  closeBtn = 'close-button',
}

export enum AppActions {
  addFormCard = 'addFormCard',
  addHomeCards = 'addHomeCards',
}
